### ISSUE TITLE
Build barebar

### ISSUE THREAD

**Issue by alexandrggdev9** [khnsky/barebar#1]
Hi, Thanks for your project.
It is very useful and I appreciate it.
Currently, I am working on a status bar project based on xcb but I am new to xcb.
Can you please tell me how to build your project?

**Comment by khnsky** [comment]
Hi,
thanks bro, hope you're doing good.

To build I think you only need to run `make` in the main folder, although you might need to install some missing libs if it can't find headers.

As for the usefulness of this project I'm not sure it has any. As you can see I haven't touched it in 2 years and I got only as far as drawing a black rectangle on the screen I think, and it's not a very good code. I think you should rather look at [yabar](https://github.com/geommer/yabar), [lemonbar](https://github.com/LemonBoy/bar) or even [polybar](https://github.com/polybar/polybar) - that's what I was doing.

Take care and good luck.
